# Generated by Django 5.2.7 on 2025-10-27 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Materials', 'Materials'), ('Location', 'Location'), ('Final Item', 'Final Item')], default='Materials', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinationsWithA', to='smithy.item')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinationsWithB', to='smithy.item')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to='smithy.item')),
            ],
        ),
    ]
