# Generated by Django 5.2.7 on 2025-10-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smithy', '0001_initial'),
    ]

    operations = [
    ]
